### ISSUE TITLE
JRE 45 and 76 only availalbe at the provided link

### ISSUE THREAD

**Issue by suidroot** [BRCDcomm/BVC#1]
When following the instructions I only found JRE 75 and 76 available, I had to browse to the following URL to find 71

http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html#sjre-7u71-oth-JPR

**Comment by udahlman** [comment]
You are correct, the links in the jre download area changed this week. 
Thanks for pointing this out, and for providing the current link to the needed version. You are correct that links to JREs can be a moving target over time and our references should reflect this fact. We will make sure to update the documentation accordingly. Thanks again!

**Comment by jebpublic** [comment]
Nice catch.  Oracle moved the location between Sunday and today.  I have updated the links below the video and placed an annotation into the video.  Thank you!
