### ISSUE TITLE
bvc-1.1.1 has bvc-base-1.1.0 alongside bvc-base-1.1.1

### ISSUE THREAD

**Issue by sonoble** [BRCDcomm/BVC#2]
It appears that the bvc-path-explorer-1.1.0 installs a older bvc-base alongside the bvc-base-1.1.1

bvc-base                              | 1.1.1            | x         | bvc-base-1.1.1                          | Brocade Vyatta Controller :: Base Distribution
bvc-base                              | 1.1.0            | x         | bvc-base-1.1.0                          | Brocade Vyatta Controller :: Base Distribution

I am not sure which one should be installed or running.  I tried to remove bvc-base-1.1.0 but it comes back on restart.

**Comment by sonoble** [comment]
vyatta-user@root>feature:list |grep bvc-base
bvc-l2switch                          | 1.1.1            |           | bvc-base-1.1.1                          | Brocade Vyatta Controller :: Layer 2 Switch
bvc-base                              | 1.1.1            | x         | bvc-base-1.1.1                          | Brocade Vyatta Controller :: Base Distribution
vyatta-user@root>logout
root@bvc-1:/opt/bvc# cd ..
root@bvc-1:/opt# unzip /home/snoble/bvc-
bvc-1.1.1.zip                             bvc-app-pathexplorer-packaging-1.1.0.zip  bvc-dependencies-1.1.1.zip
root@bvc-1:/opt# unzip /home/snoble/bvc-app-pathexplorer-packaging-1.1.0.zip
Archive:  /home/snoble/bvc-app-pathexplorer-packaging-1.1.0.zip
  inflating: bvc/.extensions/bvc-app-pathexplorer-packaging-1.1.0.zip
  inflating: bvc/bvc-app-pathexplorer-packaging-license.txt
root@bvc-1:/opt# cd bvc
root@bvc-1:/opt/bvc# ls
bin                                         bvc-dependencies.README  bvc-license.txt  install  tls       web
bvc-app-pathexplorer-packaging-license.txt  bvc-dep-license.txt      controller       log      versions
root@bvc-1:/opt/bvc# ./install
 Brocade Vyatta Controller Installation

 Starting @ : 2015-02-18 10:24:56.176893
 Adding Repositories ... please wait ...
                       ................. [ OK ]
 Installing Features ... please wait ...
                       ................. [ OK ]
 Extension Install ... please wait ...
                         ............... [ OK ]
 Stopping NODEJS: ...................... [ OK ]
 Starting NODEJS: ...................... [ OK ]
    Server @ http://192.168.21.109:9000/
 UI Installation: ...................... [ OK ]
 Install completed @ :  2015-02-18 10:25:01.111969

vyatta-user@root>feature:list | grep bvc-base
bvc-l2switch                          | 1.1.1            |           | bvc-base-1.1.1                          | Brocade Vyatta Controller :: Layer 2 Switch
bvc-base                              | 1.1.1            | x         | bvc-base-1.1.1                          | Brocade Vyatta Controller :: Base Distribution
bvc-l2switch                          | 1.1.0            |           | bvc-base-1.1.0                          | Brocade Vyatta Controller :: Layer 2 Switch
bvc-base                              | 1.1.0            | x         | bvc-base-1.1.0                          | Brocade Vyatta Controller :: Base Distribution

**Comment by jebpublic** [comment]
Yes, you are correct, for the initial release of BVC (1.1.0), the Path Explorer (PE) was tested with, and depended on, the slightly-earlier release, 1.1.0. Hence because of this dependency, PE pulls in the base bvc for 1.1.0. This is benign but PE has been updated for the next version so this will not occur.  There is no functional impact and all functions continue to operate because under the hood the “bvc-base” 1.1.1 feature and 1.1.0 feature pull in the same versions of ODL features. So the fact that bvc_base 1.1.0 is loading up isn’t a problem in this case.

**Comment by sonoble** [comment]
Thank you for the response. I am debugging an issue where the default OpenFlow drop flow is added randomly and am looking at causation. I will see if it reproduces without the path application installed.
